---

name: Build n8n image

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.**" ]
    paths: 
    - ".github/workflows/build-n8n.yml"
    - "n8n/**"
  pull_request:
    branches: [ "main" ]
    paths: 
    - ".github/workflows/build-n8n.yml"
    - "n8n/**"
  workflow_dispatch:
    inputs:
      n8n-version:
        description: "n8n version to build"

jobs:
  build-docker-image:
    uses: pirogoeth/workflows/.github/workflows/docker-generic.yml@main
    with:
      output-registry: "ghcr.io"
      output-repository-path: "${{ github.repository }}/n8n"
      dockerfile-path: "./n8n/Dockerfile"
      build-context: "./n8n/"
      image-build-args: |
        N8N_VERSION=${{ inputs.n8n-version || vars.N8N_VERSION }}
      image-tags: |
        type=raw,value=${{ inputs.n8n-version || vars.N8N_VERSION }}
