---

name: Build n8n image

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.**" ]
    paths: 
    - ".github/workflows/build-n8n.yml"
    - "n8n/**"
  pull_request:
    branches: [ "main" ]
    paths: 
    - ".github/workflows/build-n8n.yml"
    - "n8n/**"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: pirogoeth/workflows/.github/workflows/docker-generic.yml@main
      env:
        N8N_VERSION: 1.20.0
      with:
        output-registry: "ghcr.io"
        output-repository-path: "${{ github.repository }}/n8n"
        dockerfile-path: "./n8n/Dockerfile"
        image-build-args: |
          N8N_VERSION=$N8N_VERSION
        image-tags: |
          type=raw,value=$N8N_VERSION