---

name: Build sdr++ image

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.**" ]
    paths: 
    - ".github/workflows/build-sdrpp.yml"
    - "sdrpp/**"
  pull_request:
    branches: [ "main" ]
    paths: 
    - ".github/workflows/build-sdrpp.yml"
    - "sdrpp/**"
  workflow_dispatch:
    inputs:
      sdrpp-version:
        description: "sdrpp version to build"

jobs:
  build-docker-image:
    uses: pirogoeth/workflows/.github/workflows/docker-generic.yml@main
    with:
      output-registry: "ghcr.io"
      output-repository-path: "${{ github.repository }}/sdrpp"
      dockerfile-path: "./sdrpp/Dockerfile"
      image-build-args: |
        SDRPP_VERSION=${{ inputs.sdrpp-version || vars.SDRPP_VERSION }}
      image-tags: |
        type=raw,value=${{ inputs.sdrpp-version || vars.SDRPP_VERSION }}